version: 1
builder:
  configs:
  - documentation_targets:
    - Property Borrow
    - Property Carrier
    - Property Consume
    - Property Inout
    - Property Primitive
    - Property
    - Property Typed
