version: 1
builder:
  configs:
  - documentation_targets:
    - Property Borrow Primitives
    - Property Carrier Primitives
    - Property Consume Primitives
    - Property Inout Primitives
    - Property Primitive
    - Property Primitives
    - Property Typed Primitives
